<?php
header("Content-Type: application/json");

// 1. SYSTEM POOL LOGGING (Bypasses local directory permission issues)
$rawPayload = file_get_contents('php://input');
$logMessage = "[" . date('Y-m-d H:i:s') . "] INBOUND WEBHOOK HIT! -> Data: " . $rawPayload . PHP_EOL;
file_put_contents('/tmp/azampay_gateway.log', $logMessage, FILE_APPEND);

// 2. Database Connection Framework
// 2. Establish Database Connection Framework
// These variables automatically read the private connection strings generated by Railway
$host     = getenv('MYSQLHOST') ?: 'mysql.railway.internal';
$db       = getenv('MYSQLDATABASE') ?: 'railway';
$user     = getenv('MYSQLUSER') ?: 'root';
$password = getenv('MYSQLPASSWORD') ?: 'TxGqIUapIhgwhpKbqywjJXkiOWGmQVLJ';
$charset  = 'utf8mb4';


$dsn = "mysql:host=$host;dbname=$db;charset=$charset";
$options = [
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES   => false,
];

try {
    $pdo = new PDO($dsn, $user, $password, $options);
} catch (\PDOException $e) {
    // Write the exact, deep error description to the system pool log to see what failed
    file_put_contents('/tmp/azampay_gateway.log', "[DB CONNECTION ERROR DETAILED] " . $e->getMessage() . PHP_EOL, FILE_APPEND);
    
    http_response_code(500);
    echo json_encode(["status" => "error", "message" => "Database disconnect"]);
    exit;
}


$data = json_decode($rawPayload, true);
if (!$data) {
    http_response_code(200);
    echo json_encode(["status" => "ready", "message" => "Callback active in the root folder!"]);
    exit;
}

$transactionStatus = $data['transactionStatus'] ?? null; 
$reference         = $data['reference'] ?? null; 

if ($reference) {
    if ($transactionStatus === 'success') {
        try {
            $sql = "UPDATE wifi_vouchers 
                    SET status = 'SUCCESS' 
                    WHERE reference = :reference AND status = 'ASSIGNED'";
                    
            $stmt = $pdo->prepare($sql);
            $stmt->execute([':reference' => $reference]);
            
            $rows = $stmt->rowCount();
            file_put_contents('/tmp/azampay_gateway.log', "[SQL SUCCESS] Ref: $reference | Rows modified: $rows" . PHP_EOL, FILE_APPEND);

            http_response_code(200);
            echo json_encode(["status" => "success"]);
            exit;
        } catch (\PDOException $e) {
            file_put_contents('/tmp/azampay_gateway.log', "[SQL EXCEPTION Success block] " . $e->getMessage() . PHP_EOL, FILE_APPEND);
            http_response_code(500);
            exit;
        }
    } else {
        try {
            $sql = "UPDATE wifi_vouchers 
                    SET status = 'AVAILABLE', assigned_phone = NULL, reference = NULL, utilityref = NULL 
                    WHERE reference = :reference";
            $stmt = $pdo->prepare($sql);
            $stmt->execute([':reference' => $reference]);
            
            file_put_contents('/tmp/azampay_gateway.log', "[SQL REVERSED] Ref: $reference" . PHP_EOL, FILE_APPEND);
            http_response_code(200);
            exit;
        } catch (\PDOException $e) {
            file_put_contents('/tmp/azampay_gateway.log', "[SQL EXCEPTION Failure block] " . $e->getMessage() . PHP_EOL, FILE_APPEND);
            http_response_code(500);
            exit;
        }
    }
}

http_response_code(200);
echo json_encode(["status" => "ignored"]);
